### ISSUE TITLE
LiveKit 2023.04.01 启动后需要输入密码

### ISSUE THREAD

**Issue by jiegec** [AOSC-Dev/aosc-mklive#3]
LiveKit 2023.04.01 在虚拟机启动以后需要输入密码，而不是自动登录；LiveKit 2022.10.19 正常，直接进入 shell，可以启动 deploykit。

**Comment by MingcongBai** [comment]
这个问题是 systemd-firstboot 命令启动时覆盖了 KMSCON 启动配置造成的，大概是因为 systemd 252 引入的 firstboot 行为变化导致的；本问题已于 3a2505dafadc9100e86c24f28ca2e410e7d31616 修复，新发布的 LiveKit 20230412 包含此修复。

感谢你的报告！
